name: Test

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'
          cache: 'maven'

      - name: Install Tesseract
        run: |
          sudo apt-get update
          sudo apt-get install -y tesseract-ocr
          sudo apt-get install -y tesseract-ocr-eng

      - name: Setup Tesseract and tessdata
        run: |
          sudo mkdir -p /usr/share/tesseract-ocr/tessdata
          wget https://github.com/tesseract-ocr/tessdata/raw/main/eng.traineddata
          sudo mv eng.traineddata /usr/share/tesseract-ocr/tessdata/

      - name: Build and Test
        run: mvn -B verify

      - name: Upload coverage reports to Codecov
        uses: codecov/codecov-action@v5
        with:
            token: ${{ secrets.CODECOV_TOKEN }}
            slug: ANcpLua/PaperlessJava
            files: ./rest/target/site/jacoco/jacoco.xml,./services/target/site/jacoco/jacoco.xml